Here we are trying to handle an exception using lambda expressions. The exception caused here is Arithmetic Exception.
